name: rstan
channels:
  - enable_revoked
  - r
  - conda-forge
  - defaults
dependencies:
  - cmdstan
  - icu = 58
  - r-tidyverse
  - r-optparse
  - r-checkmate
  - r-posterior >=1.4.1
  - r-rlang >=1.0.6
  - r-vctrs >=0.5.0
  - r-testthat
  - r-usethis
  - r-ggnewscale

