name: rstan
channels:
  - enable_revoked
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cmdstan >= 2.34.1
  #- icu = 58
  #- icu
  - cudatoolkit
  - r-tidyverse
  - r-optparse
  - r-checkmate
  - r-posterior >=1.4.1
  - r-rlang >=1.0.6
  - r-vctrs >=0.5.0
  #- bioconductor-rtracklayer
  #- r-stringi
  #- r-stringr
  #- r-testthat
  #- r-usethis
  - r-ggnewscale

